---
- name: Install Jenkins
  hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: Update all packages to their latest version
      shell: sudo apt-get update

    - name: Download Jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repo
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list

    - name: Update all packages to their latest version
      shell: sudo apt-get update

    - name: Install Fontconfig
      shell: sudo apt install fontconfig -y

    - name: Install Java
      shell: sudo apt install openjdk-17-jre -y

    - name: Install the package Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        state: started
        name: jenkins
        enabled: true
