---
- name: Install Jenkins
  hosts: localhost
  become: yes

  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
  roles:
    - role: suzuki-shunsuke.jenkins-ubuntu
